"""Build a per-jurisdiction register of form identifiers for human review.

`docs/COVERAGE.md` records why silent misuse of a form name cannot be caught by
consistency checking: the misusing guide never defines the term, so there is no
second claim to contradict. Malta's `mt-estimated-tax` used `TA24` -- the rental
final-tax form -- twenty-four times as its name for the self-employed income tax
return, agreed with itself throughout, and passed every structural check here.

Tooling cannot close that. What tooling can do is make the human pass cheap.
This lists every form identifier used in more than one guide in a jurisdiction,
with the guides that use it, so a reviewer who knows the jurisdiction can scan a
page instead of reading a pack. The Malta defect is obvious in this shape --
a rental form appearing in a provisional-tax guide -- and takes a second to see
once the guides are listed beside the token.

Written to `docs/FORM-REGISTER.md`. Regenerate with:
    python3 scripts/build-form-register.py

Single-guide forms are omitted: a form named once cannot be inconsistent with a
sibling, and including them buried the register. Currency codes are excluded --
`USD 700` is not a form, and an early version of this listed several.
"""
import os, re, collections

FORM = re.compile(r'(?<![A-Za-z0-9])((?:[A-Z]{2,5}-?\d{1,4}[A-Z]?)|'
                  r'(?:Form\s+[A-Z0-9][\w\-/]{1,10}))(?![A-Za-z0-9])')
CUR = re.compile(r'^(USD|EUR|GBP|VES|ZAR|AUD|NZD|CAD|MXN|BRL|INR|JPY|CNY|CHF|SEK|NOK|'
                 r'DKK|PLN|RON|HUF|CZK|TRY|RUB|ILS|AED|SAR|KES|NGN|GHS|ZMW|MWK|TZS|UGX|'
                 r'MUR|LKR|PKR|BDT|IDR|MYR|THB|PHP|VND|SGD|HKD|TWD|KRW|BOB|PEN|CLP|COP)\b')
# tokens that look like forms but are laws, standards or section references
NOTFORM = re.compile(r'^(IAS|IFRS|ISA|ASC|ISO|GRI|SIC|NACE|SIC\d|COVID|G20|OECD|EU\d|IRC\d)')


def main():
    jur = collections.defaultdict(lambda: collections.defaultdict(set))
    for dp, _, fns in os.walk('skills'):
        for fn in sorted(fns):
            if not fn.endswith('.md'):
                continue
            p = os.path.join(dp, fn)
            parts = p.split(os.sep)
            if len(parts) < 3:
                continue
            text = open(p, encoding='utf-8', errors='replace').read()
            for m in FORM.finditer(text):
                tok = re.sub(r'\s+', ' ', m.group(1)).strip()
                if CUR.match(tok) or NOTFORM.match(tok):
                    continue
                jur[parts[2]][tok].add(os.path.basename(p)[:-3])

    rows = tokens = 0
    out = ['# Form register',
           '',
           'Generated by `scripts/build-form-register.py` — do not edit by hand.',
           '',
           'Every form identifier used by **more than one guide** in a jurisdiction,',
           'with the guides that use it. A form named in only one guide is omitted:',
           'it cannot disagree with a sibling.',
           '',
           'This exists because silent misuse of a form name is not detectable by',
           'consistency checking — see "Why a checker cannot close this gap" in',
           '[COVERAGE.md](COVERAGE.md). Scan for a form appearing in a guide whose',
           'subject it does not belong to: a rental form in a provisional-tax guide,',
           'a payroll form in a VAT guide. That is the shape the one confirmed',
           'instance took.',
           '']
    for j in sorted(jur):
        shared = {t: g for t, g in jur[j].items() if len(g) > 1}
        if not shared:
            continue
        out.append('## %s' % j)
        out.append('')
        out.append('| Form | Guides |')
        out.append('|---|---|')
        for t in sorted(shared):
            out.append('| `%s` | %s |' % (t, ', '.join('`%s`' % g for g in sorted(shared[t]))))
            tokens += 1
        out.append('')
        rows += 1
    out.append('---')
    out.append('')
    out.append('%d jurisdictions, %d shared form identifiers.' % (rows, tokens))
    open(os.path.join('docs', 'FORM-REGISTER.md'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print('docs/FORM-REGISTER.md: %d jurisdictions, %d shared form identifiers' % (rows, tokens))


if __name__ == '__main__':
    main()
