"""Build a per-jurisdiction register of form identifiers for human review.

`docs/COVERAGE.md` records why silent misuse of a form name cannot be caught by
consistency checking: the misusing guide never defines the term, so there is no
second claim to contradict. Malta's `mt-estimated-tax` used `TA24` -- the rental
final-tax form -- twenty-four times as its name for the self-employed income tax
return, agreed with itself throughout, and passed every structural check here.

Tooling cannot close that. What tooling can do is make the human pass cheap.
This lists every form identifier used in more than one guide in a jurisdiction,
with the guides that use it, so a reviewer who knows the jurisdiction can scan a
page instead of reading a pack. The Malta defect is obvious in this shape --
a rental form appearing in a provisional-tax guide -- and takes a second to see
once the guides are listed beside the token.

Written to `docs/FORM-REGISTER.md`. Regenerate with:
    python3 scripts/build-form-register.py

Single-guide forms are omitted: a form named once cannot be inconsistent with a
sibling, and including them buried the register. Currency codes are excluded --
`USD 700` is not a form, and an early version of this listed several.
"""
# Known gap, from the PR #16 review. The group key is the third path component,
# which for skills/federal/<guide>.md is the FILENAME rather than a jurisdiction.
# So no two federal guides can ever share a group, and a form used by both --
# Form 1099-NEC appears in us-1099-nec-issuance and us-1099-k-and-payment-
# processors -- never registers as shared. The register's federal section is
# therefore absent rather than empty, and the published total under-counts.
# Normalising those paths to a single "federal" group is the fix; it moves the
# count in docs/COVERAGE.md, so it belongs in its own change rather than here.
import os, re, collections

# The lookbehind rejects a preceding hyphen as well as a letter or digit, and
# that single character was 57% of the register. This corpus numbers its own
# refusal rules R-AL-1, R-AU-1, R-DZ-1, and a lookbehind of (?<![A-Za-z0-9])
# happily matched from after the first hyphen, so "AL-1" was filed as an
# Albanian form used by two guides. 521 of 914 identifiers were refusal codes.
# The register exists to make a human pass cheap on the one error class no
# checker can see, and more than half of it was pointing at nothing.
FORM = re.compile(r'(?<![A-Za-z0-9-])((?:[A-Z]{2,5}-?\d{1,4}[A-Z]?)|'
                  r'(?:Form\s+[A-Z0-9][\w\-/]{1,10}))(?![A-Za-z0-9])')
CUR = re.compile(r'^(USD|EUR|GBP|VES|ZAR|AUD|NZD|CAD|MXN|BRL|INR|JPY|CNY|CHF|SEK|NOK|'
                 r'DKK|PLN|RON|HUF|CZK|TRY|RUB|ILS|AED|SAR|KES|NGN|GHS|ZMW|MWK|TZS|UGX|'
                 r'MUR|LKR|PKR|BDT|IDR|MYR|THB|PHP|VND|SGD|HKD|TWD|KRW|BOB|PEN|CLP|COP)\b')
# Tokens the form pattern matches that are not forms. Each was found by reading
# the generated register: AGPL-3 is the licence line and appeared under 240
# jurisdictions; EC1-EC8 are the guides' own edge-case labels; QH12-QH14 are
# Vietnamese National Assembly sessions; "Form Structure" is a heading. A
# register full of these is worse than none, because a reviewer stops reading.
NOTFORM = re.compile(r'^(?:IAS|IFRS|ISA|ASC|ISO|GRI|SIC|NACE|COVID|G20|OECD|IRC\d'
                     r'|AGPL-?\d?|EC\d{1,2}|EU-?\d|QH\d{1,2}|CO2|FY\d{4}|INV-?\d{4}'
                     r'|T\d|TY\d{4}|R-[A-Z]{2}|Form Structure|Form Type|Form Name)$', re.I)


def selftest():
    """A refusal code is not a form, and a real form is still a form."""
    def toks(t):
        return [m.group(1) for m in FORM.finditer(t)
                if not (CUR.match(m.group(1)) or NOTFORM.match(m.group(1)))]
    assert toks('- **R-AL-1** - Residency unknown.') == [], \
        'R-AL-1 is a refusal code; its tail is not an Albanian form'
    assert toks('- **R-AU-1 -- Companies and trusts**') == []
    assert 'TA24' in toks('the prior year TA24 must be filed'), 'TA24 is a real form'
    assert 'VAT201' in toks('submit the VAT201 return')
    assert toks('paid USD 700 in fees') == [], 'a currency amount is not a form'
    print('selftest: refusal codes excluded, real forms kept')


def main():
    jur = collections.defaultdict(lambda: collections.defaultdict(set))
    for dp, _, fns in os.walk('skills'):
        for fn in sorted(fns):
            if not fn.endswith('.md'):
                continue
            p = os.path.join(dp, fn)
            parts = p.split(os.sep)
            if len(parts) < 3:
                continue
            text = open(p, encoding='utf-8', errors='replace').read()
            for m in FORM.finditer(text):
                tok = re.sub(r'\s+', ' ', m.group(1)).strip()
                if CUR.match(tok) or NOTFORM.match(tok):
                    continue
                jur[parts[2]][tok].add(os.path.basename(p)[:-3])

    rows = tokens = 0
    out = ['# Form register',
           '',
           'Generated by `scripts/build-form-register.py` — do not edit by hand.',
           '',
           'Every form identifier used by **more than one guide** in a jurisdiction,',
           'with the guides that use it. A form named in only one guide is omitted:',
           'it cannot disagree with a sibling.',
           '',
           'This exists because silent misuse of a form name is not detectable by',
           'consistency checking — see "Why a checker cannot close this gap" in',
           '[COVERAGE.md](COVERAGE.md). Scan for a form appearing in a guide whose',
           'subject it does not belong to: a rental form in a provisional-tax guide,',
           'a payroll form in a VAT guide. That is the shape the one confirmed',
           'instance took.',
           '']
    for j in sorted(jur):
        shared = {t: g for t, g in jur[j].items() if len(g) > 1}
        if not shared:
            continue
        out.append('## %s' % j)
        out.append('')
        out.append('| Form | Guides |')
        out.append('|---|---|')
        for t in sorted(shared):
            out.append('| `%s` | %s |' % (t, ', '.join('`%s`' % g for g in sorted(shared[t]))))
            tokens += 1
        out.append('')
        rows += 1
    out.append('---')
    out.append('')
    out.append('%d jurisdictions, %d shared form identifiers.' % (rows, tokens))
    open(os.path.join('docs', 'FORM-REGISTER.md'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print('docs/FORM-REGISTER.md: %d jurisdictions, %d shared form identifiers' % (rows, tokens))


if __name__ == '__main__':
    import sys
    if '--selftest' in sys.argv:
        selftest()
    else:
        main()
